engines:
  eslint:
    enabled: true
ratings:
  paths:
    - server/**/*
    - worker/**/*
    - migrations/**/*
    - seeds/**/*
    - gulpfile.js
    - knexfile.js
exclude_paths:
  - apiary/**/*
  - gulp/**/*
